export default {
  BLACK: '#000000',
  PRIMARY: '#000000',
  WHITE: '#ffffff',
  YELLOW: '#eecd04',
  GREY: '#E7E7EA',
  colorRoyalblue_100: 'rgba(97, 85, 223, 1)',
  lightblue: '#F8F8FF',
  midblue: 'rgba(97, 85, 223, 0.2)',
  textC: 'rgba(110, 118, 163, 1)',
};

export const FontFamily = {
  JockeyOne: 'JockeyOne-Regular',
  InterBlack18: 'Inter_18pt-Black',
  InterBlackItalic18: 'Inter_18pt-BlackItalic',
  InterBold18: 'Inter_18pt-Bold',
  InterBoldItalic18: 'Inter_18pt-BoldItalic',
  InterExtraBold18: 'Inter_18pt-ExtraBold',
  InterExtraBoldItalic18: 'Inter_18pt-ExtraBoldItalic',
  InterExtraLight18: 'Inter_18pt-ExtraLight',
  InterExtraLightItalic18: 'Inter_18pt-ExtraLightItalic',
  InterLight18: 'Inter_18pt-Light',
  InterLightItalic18: 'Inter_18pt-LightItalic',
  InterMedium18: 'Inter_18pt-Medium',
  InterMediumItalic18: 'Inter_18pt-MediumItalic',
  InterRegular18: 'Inter_18pt-Regular',
  InterSemiBold18: 'Inter_18pt-SemiBold',
  InterSemiBoldItalic18: 'Inter_18pt-SemiBoldItalic',
  InterThin18: 'Inter_18pt-Thin',
  InterThinItalic18: 'Inter_18pt-ThinItalic',
  InterBlack24: 'Inter_24pt-Black',
  InterBlackItalic24: 'Inter_24pt-BlackItalic',
  InterBold24: 'Inter_24pt-Bold',
  InterBoldItalic24: 'Inter_24pt-BoldItalic',
  InterExtraBold24: 'Inter_24pt-ExtraBold',
  InterExtraBoldItalic24: 'Inter_24pt-ExtraBoldItalic',
  InterExtraLight24: 'Inter_24pt-ExtraLight',
  InterExtraLightItalic24: 'Inter_24pt-ExtraLightItalic',
  InterLight24: 'Inter_24pt-Light',
  InterLightItalic24: 'Inter_24pt-LightItalic',
  InterMedium24: 'Inter_24pt-Medium',
  InterMediumItalic24: 'Inter_24pt-MediumItalic',
  InterRegular24: 'Inter_24pt-Regular',
  InterSemiBold24: 'Inter_24pt-SemiBold',
  InterSemiBoldItalic24: 'Inter_24pt-SemiBoldItalic',
  InterThin24: 'Inter_24pt-Thin',
  InterThinItalic24: 'Inter_24pt-ThinItalic',
  InterBlack28: 'Inter_28pt-Black',
  InterBlackItalic28: 'Inter_28pt-BlackItalic',
  InterBold28: 'Inter_28pt-Bold',
  InterBoldItalic28: 'Inter_28pt-BoldItalic',
  InterExtraBold28: 'Inter_28pt-ExtraBold',
  InterExtraBoldItalic28: 'Inter_28pt-ExtraBoldItalic',
  InterExtraLight28: 'Inter_28pt-ExtraLight',
  InterExtraLightItalic28: 'Inter_28pt-ExtraLightItalic',
  InterLight28: 'Inter_28pt-Light',
  InterLightItalic28: 'Inter_28pt-LightItalic',
  InterMedium28: 'Inter_28pt-Medium',
  InterMediumItalic28: 'Inter_28pt-MediumItalic',
  InterRegular28: 'Inter_28pt-Regular',
  InterSemiBold28: 'Inter_28pt-SemiBold',
  InterSemiBoldItalic28: 'Inter_28pt-SemiBoldItalic',
  InterThin28: 'Inter_28pt-Thin',
  InterThinItalic28: 'Inter_28pt-ThinItalic',
};
